version: '3.4'

services:
  blog:
    build: .
    volumes:
      - .:/blog
    ports:
      - 4006:4006
    networks:
      - default
    environment:
      - "PORT=4006"
    command: jekyll serve --host 0.0.0.0 --port 4006
